TEST1 += Navigator.scala bobsrockets.scala launch.scala
TEST1 += Fleet2.scala

TEST2 += Fruits.scala TestFruits.scala

TEST3 += Fruits.scala BobsdelightsPackage.scala
TEST3 += Printmenu.scala

test1:
	scalac $(TEST1)

test2:
	scalac $(TEST2)

test3:
	scalac $(TEST3)
